language: php
os: linux
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source
  - export PATH=./bin/:$PATH

script:
  - phing coverage

after_script:
  - php ./bin/coveralls -v
